POSTGRES_USER=hello_django
POSTGRES_PASSWORD=hello_django
POSTGRES_DB=hello_django_dev

PHP_PG_ADMIN_SERVER_HOST=db
PHP_PG_ADMIN_SERVER_PORT=5432
PHP_PG_ADMIN_DEFAULT_DB=hello_django_dev
PHP_PG_ADMIN_DEFAULT_USER=hello_django
PHP_PG_ADMIN_DEFAULT_PASS=hello_django